apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: explore
spec:
  version: {{ .TagName }}
  homepage: https://github.com/keisku/kubectl-explore
  shortDescription: A better kubectl explain with the fuzzy finder
  description: |
    Fuzzy-find and explain the fields associated with
    supported API resource.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/keisku/kubectl-explore/releases/download/{{ .TagName }}/kubectl-explore_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-explore
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/keisku/kubectl-explore/releases/download/{{ .TagName }}/kubectl-explore_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-explore
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/keisku/kubectl-explore/releases/download/{{ .TagName }}/kubectl-explore_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-explore
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/keisku/kubectl-explore/releases/download/{{ .TagName }}/kubectl-explore_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-explore
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/keisku/kubectl-explore/releases/download/{{ .TagName }}/kubectl-explore_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-explore.exe
